default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  sim: False
  pickle_fn: ../assets/scooping_parsed_with_embeddings_moco_conv5.pkl
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  H: 16 # horizon of actions to predict each time
  top_k: null
  images:
    cameras: []
    im_h: 480
    im_w: 640
    per_img_out: 2048
    crop: True
  noise: 0.0

agent:
  type: 'bcimage_pre'
  # vision_model: 'moco_conv5'
  vision_model: 'collaborator_encoder'
  # TODO (Optional): If you use a custom vision_model, optionally specify the path to your model here
  # vision_model_path won't be used if you use an existing TOTO vision_model.
  # TODO (Optional): additional keys (if any) for initializing your vision model should go here. 
  vision_model_path: '/data/sabarish/CelebBasis_photoverse/infer_images/ti/toto/toto_benchmark_subm/toto_benchmark/vision/deltas_moco_joint.pth'
  description: NA
  hidden_dim: 128

training:
  lr: 1e-4
  seed: 0
  epochs: 200
  device: 'cuda'
  batch_size: 128
  save_every_x_epoch: 10

debug: False
