default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  # part 0 of sim data
  sim: True
  pickle_fn: sim/dm_human_dataset.pickle
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  H: 16 # horizon of actions to predict each time
  top_k: null
  images:
    cameras: []
    im_h: 240
    im_w: 320
    per_img_out: 2048
    crop: True
  noise: 0.0

agent:
  type: 'Diffusion_policy_unet'
  vision_model: 'moco_conv5'
  # When using Deltas_Forced_MOCO, repalce the trained checkpoint path
  # vision_model_path: './15.pth'
  description: NA
  hidden_dim: 2048

training:
  lr: 1e-4
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 128
  save_every_x_epoch: 10

debug: False
